# Generated by Django 2.1.4 on 2019-01-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATest',
            fields=[
                ('tID', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('tName', models.CharField(max_length=30)),
                ('tDescribe', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('dID', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('dName', models.CharField(max_length=30)),
                ('tID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ATest')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('oID', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('oName', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('dID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qID', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('qName', models.CharField(max_length=30)),
                ('tID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ATest')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='qID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Question'),
        ),
    ]
