# Generated by Django 2.1.4 on 2019-01-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATest',
            fields=[
                ('t_id', models.AutoField(db_column='t_id', primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=30)),
                ('t_describe', models.CharField(max_length=80)),
                ('u_id', models.IntegerField()),
                ('t_status', models.IntegerField()),
                ('t_due', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('d_id', models.AutoField(db_column='d_id', primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=30)),
                ('t_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('j_id', models.AutoField(db_column='j_id', primary_key=True, serialize=False)),
                ('j_content', models.CharField(max_length=200)),
                ('t_id', models.IntegerField()),
                ('d_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('o_id', models.AutoField(db_column='o_id', primary_key=True, serialize=False)),
                ('o_name', models.CharField(max_length=30)),
                ('q_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('d_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.AutoField(db_column='q_id', primary_key=True, serialize=False)),
                ('q_name', models.CharField(max_length=30)),
                ('t_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(db_column='record_id', primary_key=True, serialize=False)),
                ('t_id', models.IntegerField()),
                ('q_id', models.IntegerField()),
                ('o_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(db_column='result_id', primary_key=True, serialize=False)),
                ('t_id', models.IntegerField()),
                ('d_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(db_column='u_id', primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=30)),
            ],
        ),
    ]
