# Generated by Django 2.1.4 on 2019-01-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atest',
            name='tID',
            field=models.IntegerField(db_column='tId', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dID',
            field=models.IntegerField(db_column='dID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='oID',
            field=models.IntegerField(db_column='oID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='qID',
            field=models.IntegerField(db_column='qID', primary_key=True, serialize=False),
        ),
    ]
