# Generated by Django 2.1.4 on 2019-01-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('j_id', models.AutoField(db_column='j_id', primary_key=True, serialize=False)),
                ('u_content', models.CharField(max_length=200)),
                ('t_id', models.IntegerField()),
                ('d_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='atest',
            name='t_id',
            field=models.AutoField(db_column='t_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='d_id',
            field=models.AutoField(db_column='d_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='o_id',
            field=models.AutoField(db_column='o_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.AutoField(db_column='q_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_id',
            field=models.AutoField(db_column='u_id', primary_key=True, serialize=False),
        ),
    ]
