# Generated by Django 2.1.4 on 2019-01-09 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190109_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='u_content',
            new_name='j_content',
        ),
    ]
